### ISSUE TITLE
feature/Java11 JMockit tests are failing

### ISSUE THREAD

**Issue by jlau78** [jlau78/whitbreadSpring#4]

**Comment by jlau78** [comment]
Running in Eclipse on Jdk1.8 tests are passing. However when running in JDK 11.0.2 using "mvn test" the test fails with these errors:

Looks like there are issues even launching the JDK11 VM in Eclipse 2018-19. This issue may be related.

[INFO] Running com.jlau78.common.exceptions.ExceptionHandlerTest
java.lang.RuntimeException: java.io.IOException: Can not attach to current VM

Caused by: java.io.IOException: Can not attach to current VM
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:48)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
        at mockit.internal.startup.AgentLoader.attachToRunningVM(AgentLoader.java:133)
